[versions]
agp = "8.3.1"
androidxAppcompat = "1.7.0"
androidxCoreKtx = "1.13.1"
appcompatVersion = "1.6.0"
coreKtxVersion = "1.9.0"
dagger = "2.51"
daggerAndroidProcessor = "2.24"
daggerAndroidProcessorVersion = "2.15"
daggerAndroidSupport = "2.24"
daggerCompiler = "2.5.1"
daggerCompilerVersion = "2.44"
daggerVersion = "2.5.1"
googleDagger = "2.44"
googleMaterial = "1.12.0"
javaxInjectVersion = "1"
jsr250ApiVersion = "1.0"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
kotlinxMetadataJvm = "0.5.0"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
jetbrainsKotlinJvm = "1.9.0"
materialVersion = "1.8.0"
navigationFragmentKtx = "2.5.3"
navigationUiKtx = "2.7.7"
navigationUiKtxVersion = "2.5.3"
okhttp = "4.9.0"
retrofit = "2.9.0"

[libraries]
androidx-appcompat-v160 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1131 = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-core-ktx-v190 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-fragment-ktx-v253 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx-v253 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
annotation-jsr250-api = { module = "javax.annotation:jsr250-api", version.ref = "jsr250ApiVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "daggerAndroidSupport" }
dagger-android-processor-v224 = { module = "com.google.dagger:dagger-android-processor", version.ref = "daggerAndroidProcessor" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "daggerAndroidSupport" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-compiler-v244 = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerCompilerVersion" }
dagger-compiler-v251 = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerCompiler" }
dagger-v244 = { module = "com.google.dagger:dagger", version.ref = "googleDagger" }
dagger-v251 = { module = "com.google.dagger:dagger", version.ref = "daggerVersion" }
google-dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "daggerAndroidProcessorVersion" }
inject-javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInjectVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
material-v180 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

